export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  GESTOR = 'GESTOR',
  FARMACEUTICO = 'FARMACEUTICO',
  AUDITOR = 'AUDITOR',
  OPERADOR = 'OPERADOR',
  USUARIO = 'USUARIO',
}

export enum FormaFarmaceutica {
  COMPRIMIDO = 'COMPRIMIDO',
  CAPSULA = 'CAPSULA',
  SOLUCAO = 'SOLUCAO',
  SUSPENSAO = 'SUSPENSAO',
  INJETAVEL = 'INJETAVEL',
  SERINGA_PREENCHIDA = 'SERINGA_PREENCHIDA',
  FRASCO_AMPOLA = 'FRASCO_AMPOLA',
  CREME = 'CREME',
  POMADA = 'POMADA',
  OUTRA = 'OUTRA',
}

export enum ClasseCEAF {
  GRUPO_1A = 'GRUPO_1A',
  GRUPO_1B = 'GRUPO_1B',
  GRUPO_2 = 'GRUPO_2',
  GRUPO_3 = 'GRUPO_3',
  CEAF = 'CEAF',
  BASICO = 'BASICO',
  ESTRATEGICO = 'ESTRATEGICO',
}

export enum TipoMovimentacao {
  ENTRADA = 'ENTRADA',
  SAIDA = 'SAIDA',
  TRANSFERENCIA = 'TRANSFERENCIA',
  DEVOLUCAO = 'DEVOLUCAO',
  AJUSTE = 'AJUSTE',
}
